### ISSUE TITLE
Footer breaking in small screens

### ISSUE THREAD

**Issue by Rithvik-padma** [samyabrata-maji/agency-site#49]
The footer of the landing page is breaking in mobile view/small screen.

Now it is like this after my changes-

![image](https://github.com/samyabrata-maji/agency-site/assets/99183441/aa14437e-f402-47fd-a71d-6d5926fc5753)

**Comment by Rithvik-padma** [comment]
@samyabrata-maji PR #48 resolves it  
Please check it!

**Comment by samyabrata-maji** [comment]
Thanks for fixing it!
